<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-annotationsf3) on 2019-03-19 18:11:41.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * AppBundle\Entity\Layout
 *
 * @ORM\Entity()
 * @ORM\Table(name="Layout")
 * @ORM\HasLifecycleCallbacks()
 */
class Layout
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $referencia;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    protected $tipo;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $valor;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $visual;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $imagen;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected $clase;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $creado;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $actualizado;

    public function __construct()
    {
    }

    public function __toString()
    {
        return (string) $this->id;
    }

    /**
    * Gets triggered only on insert
    * @ORM\PrePersist
    */
    public function onPrePersist(){
        $this->creado = new \DateTime("now"); 
    }

    /**
    * Gets triggered only on update
    * @ORM\PreUpdate
    */
    public function onPreUpdate(){
        $this->actualizado = new \DateTime("now"); 
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \AppBundle\Entity\Layout
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of referencia.
     *
     * @param string $referencia
     * @return \AppBundle\Entity\Layout
     */
    public function setReferencia($referencia)
    {
        $this->referencia = $referencia;

        return $this;
    }

    /**
     * Get the value of referencia.
     *
     * @return string
     */
    public function getReferencia()
    {
        return $this->referencia;
    }

    /**
     * Set the value of tipo.
     *
     * @param integer $tipo
     * @return \AppBundle\Entity\Layout
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;

        return $this;
    }

    /**
     * Get the value of tipo.
     *
     * @return integer
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * Set the value of valor.
     *
     * @param string $valor
     * @return \AppBundle\Entity\Layout
     */
    public function setValor($valor)
    {
        $this->valor = $valor;

        return $this;
    }

    /**
     * Get the value of valor.
     *
     * @return string
     */
    public function getValor()
    {
        return $this->valor;
    }

    /**
     * Set the value of visual.
     *
     * @param string $visual
     * @return \AppBundle\Entity\Layout
     */
    public function setVisual($visual)
    {
        $this->visual = $visual;

        return $this;
    }

    /**
     * Get the value of visual.
     *
     * @return string
     */
    public function getVisual()
    {
        return $this->visual;
    }

    /**
     * Set the value of imagen.
     *
     * @param string $imagen
     * @return \AppBundle\Entity\Layout
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get the value of imagen.
     *
     * @return string
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * Set the value of clase.
     *
     * @param string $clase
     * @return \AppBundle\Entity\Layout
     */
    public function setClase($clase)
    {
        $this->clase = $clase;

        return $this;
    }

    /**
     * Get the value of clase.
     *
     * @return string
     */
    public function getClase()
    {
        return $this->clase;
    }

    /**
     * Set the value of creado.
     *
     * @param \DateTime $creado
     * @return \AppBundle\Entity\Layout
     */
    public function setCreado($creado)
    {
        $this->creado = $creado;

        return $this;
    }

    /**
     * Get the value of creado.
     *
     * @return \DateTime
     */
    public function getCreado()
    {
        return $this->creado;
    }

    /**
     * Set the value of actualizado.
     *
     * @param \DateTime $actualizado
     * @return \AppBundle\Entity\Layout
     */
    public function setActualizado($actualizado)
    {
        $this->actualizado = $actualizado;

        return $this;
    }

    /**
     * Get the value of actualizado.
     *
     * @return \DateTime
     */
    public function getActualizado()
    {
        return $this->actualizado;
    }

    public function __sleep()
    {
        return array('id', 'referencia', 'tipo', 'valor', 'visual', 'imagen', 'clase', 'creado', 'actualizado');
    }
}